packages:
  - "."
  - "packages/pc-react/content/*"
  - "sdks/*"
  - "sdks/sdkwork-music-app-sdk/*/generated/server-openapi"
  - "sdks/sdkwork-music-backend-sdk/*/generated/server-openapi"
  - "../../javasource/spring-ai-plus/spring-ai-plus-business/apps/sdkwork-core/sdkwork-core-pc-react"
  - "../../javasource/spring-ai-plus/spring-ai-plus-business/apps/sdkwork-ui/sdkwork-ui-pc-react"
  - "../../javasource/spring-ai-plus/spring-ai-plus-business/spring-ai-plus-app-api/sdkwork-sdk-app/sdkwork-app-sdk-typescript"
  - "../../javasource/spring-ai-plus/sdk/sdkwork-sdk-commons/sdkwork-sdk-common-typescript"

catalog:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  jsdom: ^29.0.1
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ~6.0.2
  vite: ^8.0.3
  vitest: ^4.1.8
