//! Generated gateway bootstrap for sdkwork-music.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;

pub struct ApiAssembly {
    pub router: Router,
}

pub fn assemble_api_router() -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_music_app_api::gateway_mount());
    router = router.merge(sdkwork_routes_music_backend_api::gateway_mount());
    ApiAssembly { router }
}
